### ISSUE TITLE
Why pass function in to= to tohil.call?

### ISSUE THREAD

**Issue by wusspuss** [flightaware/tohil#87]
>The optional to= named parameter can specify a Python data type to return, such as str, int, float, bool, list, set, dict, tuple, tohil.tclobj, tohil.tcldict, or a **function that takes one argument and returns a result**.

Judging from the source code the function will be called with the result of the tcl call as TohilTclObj, so it's like continuation passing style? Just wondering what the point of it is?

**Comment by NasaGeek** [comment]
I'm not quite sure what your reference to "continuation passing style" means, but one particular case where we've found this behavior useful is when a timestamp of some sort is returned from a Tcl proc. Consider a proc that returns epoch timestamps which we would like to be transformed into python `datetime`. You could pass `to=datetime.fromtimestamp` in order to receive a `datetime` back from `tohil.call()` or the `tohil.TclProc`.

Let me know if I've misunderstood the confusion.

**Comment by wusspuss** [comment]
Ah ok, I see. Although I don't see a reason for doing this over the standard `datetime.fromtimestamp(tohil.call(...))` but anyway.
By continuation passing style I meant the hack people today mostly use for concurrency (aka callback hell), I almost thought this was intended for some trickery to integrate tcl coroutines to python
